<a href="https://colab.research.google.com/github/rkat7/torch-notes/blob/main/torch_running_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.5.1+cu124'

# Tensors are fundamental building block of Machine Learning.
# their job is to represent data in a numeric way

#tensor is a scalar with dimensions?
# because scalar is tensor with 0 dimensions


In [ ]:
scalar = torch.tensor(5)
scalar
scalar.type

<function Tensor.type>

In [ ]:
vector = torch.tensor([1,2])
print(vector)
print(vector.type)
print(vector.ndim)


tensor([1, 2])
<built-in method type of Tensor object at 0x7d3df5bca810>
1


In [ ]:
matrix = torch.tensor([[1,2,3],[3,4,5],[6,7,8]])
print(matrix)
print(matrix.type)
print(matrix.ndim)
print(matrix.shape)
print(matrix.size())

torch.Size([3, 3])


In [ ]:
random_tensor = torch.rand(size=(5,6,7))
random_tensor

# random_tensor.ndim
# random_tensor.shape
# random_tensor.size()


tensor([[[0.2414, 0.5409, 0.8426, 0.1564, 0.2791, 0.0479, 0.3396],
         [0.2371, 0.9677, 0.0490, 0.9792, 0.4546, 0.0972, 0.0843],
         [0.1648, 0.6131, 0.9204, 0.1016, 0.6278, 0.4452, 0.9655],
         [0.7441, 0.9926, 0.5067, 0.0076, 0.6233, 0.2840, 0.0306],
         [0.6148, 0.7150, 0.1819, 0.7729, 0.8084, 0.2153, 0.0588],
         [0.3002, 0.7350, 0.2285, 0.7211, 0.9095, 0.8843, 0.3022]],

        [[0.2649, 0.0851, 0.3882, 0.9598, 0.2777, 0.1187, 0.5347],
         [0.8515, 0.9051, 0.5980, 0.8833, 0.3072, 0.7971, 0.6391],
         [0.6208, 0.9105, 0.4487, 0.9765, 0.9452, 0.4385, 0.4663],
         [0.6993, 0.2953, 0.0155, 0.8265, 0.5980, 0.6168, 0.9412],
         [0.0780, 0.9217, 0.1971, 0.1769, 0.1734, 0.0847, 0.0489],
         [0.4079, 0.8465, 0.3853, 0.1568, 0.7469, 0.3932, 0.0406]],

        [[0.1502, 0.3446, 0.8491, 0.9175, 0.1654, 0.8057, 0.3877],
         [0.9325, 0.1118, 0.2411, 0.6679, 0.3076, 0.2440, 0.3916],
         [0.8869, 0.7370, 0.9760, 0.4890, 0.0318, 0.8727, 

# Might often wanna create a tensor with just 0s or 1s

# particularly for masking

In [ ]:
zeros = torch.zeros(size=(4,5))
ones = torch.ones(size=(4,5))
print(zeros)
print(ones)

print(ones.type, zeros.type)
print(ones.ndim, zeros.ndim)
print(ones.dtype, zeros.dtype)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
<built-in method type of Tensor object at 0x7d3d0ac79eb0> <built-in method type of Tensor object at 0x7d3d0ac7a570>
2 2
torch.float32 torch.float32


In [ ]:
range_tensor = torch.arange(1,10,1)
range_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# mimicking a tensor but with zeros or ones (wrt the shape)
mimicked_zeros = torch.zeros_like(zeros)
print(mimicked_zeros)

mimicked_ones = torch.ones_like(ones)
print(mimicked_ones)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


# plenty of dtypes available in pytorch
# each its own use
# precision varies across use cases - so gotta use appropriate dtype



In [ ]:
#default dtype is float32

example_tensor = torch.tensor([1,2,3], dtype=None, device=None, requires_grad=False)
#requires_grad - gradient - It records operations performed on the tensor

example_tensor.shape, example_tensor.dtype, example_tensor.device

(torch.Size([3]), torch.int64, device(type='cpu'))



> Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.



# debug song
> what, what, where:

> shape, dtype, device





```
tensor * tensor -> element wise multiplication

torch.matmul(tensor, tensor) -> matrix multiplication

tensor @ tensor -> matrix multiplicaiton (python convnetion)
```



In [ ]:
%%time

tensor = torch.arange(1,11,1)

print(tensor)

for i in range(len(tensor)):
  tensor[i] += tensor[i]

tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
CPU times: user 2.67 ms, sys: 0 ns, total: 2.67 ms
Wall time: 5.37 ms


tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# matrix transpose to the rescue
#Use:
#tensor.T
#OR
#torch.transpose(tensor, dim0, dim1)


In [ ]:
#torch.mm() is short for .matmul()

In [ ]:
# aggregations

x = torch.arange(1,10,1)

x.max(), x.min()

x.sum(), x.type(torch.float64).mean()

x.type(torch.float16).mean()


tensor(5., dtype=torch.float16)

In [ ]:
#find index where max or min occurs

print(f"index of max in tensor x {x.argmax()}")
print(f"index of min in tensor x {x.argmin()}")

index of max in tensor x 8
index of min in tensor x 0


In [ ]:
#to solve the problem of shape we saw - Transpose
# now to solve datatype...

Tensor1, Tensor2 = torch.arange(1,10,1), torch.arange(1., 10., 1.)
print(Tensor1.dtype, Tensor2.dtype)

#you can change the tensor x's type by - x.type(dtype=None)

# so swapping types now

Tensor1, Tensor2 = Tensor1.type(torch.float32), Tensor2.type(torch.int64)
print(Tensor1.dtype, Tensor2.dtype)




torch.int64 torch.float32
torch.float32 torch.int64


In [ ]:
# reshaping, stacking, squeezing and unsqueezing, permute

Tensor3 = torch.stack([Tensor1, Tensor2], 0)
Tensor4 = torch.stack([Tensor1, Tensor2], 1)
Tensor1.shape, Tensor2.shape, Tensor3.shape
Tensor3

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#indexing of tensors goes from outer index --> inner index

t = torch.arange(1,10,1).reshape(1,3,3)

t

t[:][:][:]

t[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
#pytorch tensors and numpy arrays

# torch.from_numpy(ndarray)
# torch.Tensor.numpy()

# default numpy arrays dtype - float64
# default torch tensors - float32




In [ ]:
#reproducability in torch
# taking out a bit of randomness

import torch
import random\

# torch.manual_seed(RANDOM_SEED)
# torch.random.manual_seed(RANDOM_SEED)

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
# torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
!nvidia-smi


Sun Feb 23 21:12:44 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   37C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
tensor = torch.tensor(4)
tensor.device


device = "cuda" if torch.cuda.is_available() else tensor.device

device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
#important to write device-agnostic code in pytorch

#moving code to a device

# tensor.to(device) this just creates a copy
#gotta resassin to overwrite
print(torch.device)
tensor_on_gpu = tensor.to(device)

tensor_on_gpu


<class 'torch.device'>


tensor(4, device='cuda:0')

In [ ]:
#moving back to cpu -  might need when you want to interact with numpy as numpy doesn't do gpus

#tensor_on_gpu.numpy() -> returns error

tensor_on_gpu.cpu().numpy()

array(4)